with
    source as (select * from {{ source("simplize", "fct_pnl") }}),

    renamed as (
        select 
            stock_code as fk_stock_id,
            quarter as quarter,
            date_trunc(
                'QUARTER',
                make_date(
                    cast(substring(quarter, 1, 4) as int),
                    (cast(substring(quarter, 6, 1) as int) - 1) * 3 + 1,
                    1
                )
            )::date as quarter_start_date,
            `doanh_thu_bán_hàng_và_cung_cấp_dịch_vụ` as sales_revenue,
            `các_khoản_giảm_trừ_doanh_thu` as revenue_deductions,
            `doanh_thu_thuần_về_bán_hàng_và_cung_cấp_dịch_vụ` as net_sales,
            `giá_vốn_hàng_bán` as cogs,
            `lợi_nhuận_gộp_về_bán_hàng_và_cung_cấp_dịch_vụ` as gross_profit_from_sales,
            `doanh_thu_hoạt_động_tài_chính` as financial_income,
            `chi_phí_tài_chính` as financial_expense,
            `chi_phí_lãi_vay` as interest_expense,
            `lợi_nhuận_từ_công_ty_liên_doanh_liên_kết` as assoc_profit,
            `chi_phí_bán_hàng` as selling_expense,
            `chi_phí_quản_lý_doanh_nghiệp` as admin_expense,
            `lợi_nhuận_thuần_từ_hoạt_động_kinh_doanh` as operating_profit,
            `lợi_nhuận_khác` as other_profit,
            `thu_nhập_khác` as other_income,
            `chi_phí_khác` as other_expense,
            `lợi_nhuận_kế_toán_trước_thuế` as pretax_profit,
            `thuế_thu_nhập_doanh_nghiệp` as income_tax,
            `chi_phí_thuế_thu_nhập_hiện_hành` as current_tax,
            `chi_phí_thuế_thu_nhập_hoãn_lại` as deferred_tax,
            `lợi_nhuận_kế_toán_sau_thuế` as net_profit,
            `lợi_nhuận_cổ_đông_công_ty_mẹ` as parent_profit,
            `lợi_nhuận_cổ_đông_thiểu_số` as minority_profit,
            `thu_nhập_lãi_thuần` as net_interest_income,
            `thu_nhập_lãi_và_các_khoản_thu_nhập_tương_tự` as interest_income,
            `chi_phí_lãi_và_các_chi_phí_tương_tự` as interest_expense_and_similar_costs,
            `lãi/lỗ_thuần_từ_hoạt_động_dịch_vụ` as net_service_profit,
            `thu_nhập_từ_hoạt_động_dịch_vụ` as service_income,
            `chi_phí_hoạt_động_dịch_vụ` as service_expense,
            `lãi/lỗ_thuần_từ_hoạt_động_kinh_doanh_ngoại_hối_và_vàng` as forex_gold_profit,
            `lãi/lỗ_thuần_từ_mua_bán_chứng_khoán_kinh_doanh` as trading_securities_profit,
            `lãi/lỗ_thuần_từ_mua_bán_chứng_khoán_đầu_tư` as investment_securities_profit,
            `lãi/lỗ_thuần_từ_hoạt_động_khác` as other_activities_profit,
            `thu_nhập_từ_hoạt_động_khác` as other_activities_income,
            `chi_phí_hoạt_động_khác` as other_activities_expense,
            `thu_nhập_từ_góp_vốn_mua_cổ_phần` as equity_investment_income,
            `tổng_thu_nhập_hoạt_động` as total_operating_income,
            `chi_phí_hoạt_động` as operating_expense,
            `lợi_nhuận_thuần_từ_hoạt_động_kinh_doanh_trước_chi_phí_dự_phòng_rủi_ro_tín_dụng` as net_operating_profit_before_provision,
            `chi_phí_dự_phòng_rủi_ro_tín_dụng` as credit_risk_provision,
            `doanh_thu_hoạt_động` as operating_revenue,
            `lãi_từ_các_tài_sản_tài_chính_ghi_nhận_thông_qua_lãi/lỗ_fvtpl` as fvtpl_assets_profit,
            `lãi_bán_các_tài_sản_tài_chính` as financial_assets_sale_profit,
            `chênh_lệch_tăng_đánh_giá_lại_các_tài_sản_tài_chính_thông_qua_lãi/lỗ` as revaluation_gain,
            `cổ_tức_tiền_lãi_phát_sinh_từ_tài_sản_tài_chính_fvtpl` as fvtpl_dividend_income,
            `lãi_từ_các_khoản_đầu_tư_nắm_giữ_đến_ngày_đáo_hạn_htm` as htm_investment_profit,
            `lãi_từ_các_khoản_cho_vay_và_phải_thu` as loan_receivable_profit,
            `lãi_từ_các_tài_sản_tài_chính_sẵn_sàng_để_bán_afs` as afs_assets_profit,
            `lãi_từ_các_công_cụ_phát_sinh_phòng_ngừa_rủi_ro` as hedging_instruments_profit,
            `doanh_thu_từ_hoạt_động_môi_giới_chứng_khoán` as brokerage_income,
            `doanh_thu_bảo_lãnh_phát_hành_chứng_khoán` as underwriting_income,
            `doanh_thu_đại_lý_phát_hành_chứng_khoán` as agency_income,
            `doanh_thu_hoạt_động_tư_vấn_đầu_tư_chứng_khoán` as investment_advisory_income,
            `doanh_thu_hoạt_động_ủy_thác_đấu_giá` as auction_income,
            `doanh_thu_lưu_ký_chứng_khoán` as custody_income,
            `doanh_thu_hoạt_động_đầu_tư_chứng_khoán_góp_vốn` as investment_income,
            `thu_cho_thuê_sử_dụng_tài_sản` as asset_rental_income,
            `doanh_thu_hoạt_động_tư_vấn_tài_chính` as financial_advisory_income,
            `doanh_thu_khác` as other_revenue,
            `doanh_thu_thuần` as net_revenue,
            `chi_phí_hoạt_động_kinh_doanh` as business_expense,
            `lỗ_các_tài_sản_tài_chính_ghi_nhận_thông_qua_lãi_lỗ_fvtpl` as fvtpl_assets_loss,
            `lỗ_bán_các_tài_sản_tài_chính` as financial_assets_sale_loss,
            `chênh_lệch_giảm_đánh_giá_lại_các_tài_sản_tài_chính_fvtpl` as revaluation_loss,
            `chi_phí_giao_dịch_mua_các_tài_sản_tài_chính_fvtpl` as fvtpl_transaction_cost,
            `lỗ_các_khoản_đầu_tư_nắm_giữ_đến_ngày_đáo_hạn_htm` as htm_investment_loss,
            `chi_phí_lãi_vay_lỗ_từ_các_khoản_cho_vay_và_phải_thu` as loan_receivable_loss,
            `lỗ_và_ghi_nhận_chênh_lệch_đánh_giá_theo_giá_trị_hợp_lý_tài_sản_tài_chính_sẵn_sàng_để_bán_afs` as afs_assets_loss,
            `chi_phí_dự_phòng_tài_sản_tài_chính_xử_lý_tổn_thất_các_khoản_phải_thu_khó_đòi_và_lỗ_suy_giảm_tài_sản_tài_chính_và_cổ_phiếu_đi_vay` as financial_assets_provision,
            `lỗ_từ_các_tài_sản_tài_chính_phái_sinh_phòng_ngừa_rủi_ro` as hedging_instruments_loss,
            `chi_phí_hoạt_động_tự_doanh` as proprietary_trading_expense,
            `chi_phí_môi_giới_chứng_khoán` as brokerage_expense,
            `chi_phí_hoạt_động_bảo_lãnh_đại_lý_phát_hành_chứng_khoán` as underwriting_expense,
            `chi_phí_tư_vấn_đầu_tư_chứng_khoán` as investment_advisory_expense,
            `chi_phí_hoạt_động_đấu_giá_ủy_thác` as auction_expense,
            `chi_phí_lưu_ký_chứng_khoán` as custody_expense,
            `chi_phí_hoạt_động_tư_vấn_tài_chính` as financial_advisory_expense,
            `chi_phí_các_dịch_vụ_khác` as other_services_expense,
            `lợi_nhuận_gộp` as gross_profit,
            `chênh_lệch_lãi_tỷ_giá_hối_đoái_đã_và_chưa_thực_hiện` as forex_gain,
            `doanh_thu_dự_thu_cổ_tức_lãi_tiền_gửi_không_cố_định_phát_sinh_trong_kỳ` as dividend_interest_income,
            `lãi_bán_thanh_lý_các_khoản_đầu_tư_vào_công_ty_con_liên_kết_liên_doanh` as investment_disposal_profit,
            `doanh_thu_khác_về_đầu_tư` as other_investment_income,
            `chênh_lệch_lỗ_tỷ_giá_hối_đoái_đã_và_chưa_thực_hiện` as forex_loss,
            `lỗ_bán_thanh_lý_các_khoản_đầu_tư_vào_công_ty_con_liên_kết_liên_doanh` as investment_disposal_loss,
            `chi_phí_dự_phòng_suy_giảm_giá_trị_các_khoản_đầu_tư_tài_chính_dài_hạn` as long_term_investment_provision,
            `chi_phí_tài_chính_khác` as other_financial_expense,
            `chi_phí_quản_lý_công_ty_chứng_khoán` as securities_management_expense,
            `kết_quả_hoạt_động` as operating_result,
            `doanh_thu_phí_bảo_hiểm` as insurance_fee_income,
            `phí_bảo_hiểm_gốc` as original_insurance_fee,
            `phí_nhận_tái_bảo_hiểm` as reinsurance_fee,
            `tăng_dự_phòng_phí_bảo_hiểm_gốc_và_nhận_tái_bảo_hiểm` as insurance_provision_increase,
            `phí_nhượng_tái_bảo_hiểm` as reinsurance_transfer_fee,
            `tổng_phí_nhượng_tái_bảo_hiểm` as total_reinsurance_transfer_fee,
            `tăng_dự_phòng_phí_nhượng_tái_bảo_hiểm` as reinsurance_provision_increase,
            `doanh_thu_phí_bảo_hiểm_thuần` as net_insurance_fee_income,
            `hoa_hồng_nhượng_tái_bảo_hiểm_và_doanh_thu_khác_hoạt_động_kinh_doanh_bảo_hiểm` as reinsurance_commission_and_other_insurance_income,
            `hoa_hồng_nhượng_tái_bảo_hiểm` as reinsurance_commission,
            `doanh_thu_khác_hoạt_động_kinh_doanh_bảo_hiểm` as other_insurance_income,
            `doanh_thu_thuần_hoạt_động_kinh_doanh_bảo_hiểm` as net_insurance_income,
            `chi_bồi_thường` as compensation_expense,
            `tổng_chi_bồi_thường` as total_compensation_expense,
            `các_khoản_giảm_trừ` as deductions,
            `thu_bồi_thường_nhượng_tái_bảo_hiểm` as reinsurance_compensation_income,
            `tăng/giảm_dự_phòng_toán_học` as math_provision_change,
            `tăng_dự_phòng_bồi_thường_bảo_hiểm_gốc_và_nhận_tái_bảo_hiểm` as insurance_compensation_provision_increase,
            `tăng_dự_phòng_bồi_thường_nhượng_tái_bảo_hiểm` as reinsurance_compensation_provision_increase,
            `tổng_chi_bồi_thường_bảo_hiểm` as total_insurance_compensation_expense,
            `tăng_dự_phòng_dao_động_lớn` as large_fluctuation_provision_increase,
            `sử_dụng_từ_dự_phòng_dao_động_lớn` as large_fluctuation_provision_usage,
            `chi_phí_khác_hoạt_động_bảo_hiểm` as other_insurance_expense,
            `chi_hoa_hồng_bảo_hiểm_gốc` as original_insurance_commission,
            `chi_phí_khác_hoạt_động_bảo_hiểm_gốc` as other_original_insurance_expense,
            `chi_khác_nhận_tái_bảo_hiểm_khác` as other_reinsurance_expense,
            `chi_nhượng_tái_bảo_hiểm` as reinsurance_transfer_expense,
            `tổng_chi_phí_hoạt_động_kinh_doanh_bảo_hiểm` as total_insurance_business_expense,
            `lợi_nhuận_gộp_hoạt_động_kinh_doanh_bảo_hiểm` as gross_insurance_profit,
            `lợi_nhuận_thuần_từ_hoạt_động_kinh_doanh_bảo_hiểm` as net_insurance_profit,
            `lợi_nhuận_hoạt_động_tài_chính` as financial_profit,
            `doanh_thu_tài_chính` as financial_revenue,
            `lợi_nhuận_hoạt_động_đầu_tư_bất_động_sản` as real_estate_investment_profit,
            `lợi_nhuận_thuần_hoạt_động_ngân_hàng` as net_banking_profit,
            `lợi_nhuận_hoạt_động_khác` as other_operating_profit,
            `thu_nhập_khác_ròng` as net_other_income
        from source
    )

select *
from renamed
